Create dua_tutorial.md
PennLINC/PennLINC.github.io pull request #67
Opened 2021-07-29 23:45 UTC by YumekaMengjiaLYU

first draft

2021-07-29 23:48 UTC, YumekaMengjiaLYU commented
@scovitz

2021-07-30 04:20 UTC, scovitz commented on docs/nda/dua_tutorial.md
> +🌟If you need to access some data from the [NIMH Data Arhive](https://nda.nih.gov/) but do not have access to it, you've come to the right place!
"If you need to download some data" instead of "If you need to access some data"

2021-07-30 04:20 UTC, scovitz commented on docs/nda/dua_tutorial.md
> +Next you need to fill out the form (don't forget to add yourself as a recipient) and have Ted sign it.
add commas after "Next" and the parenthetical

2021-07-30 04:35 UTC, scovitz commented on docs/nda/dua_tutorial.md
> +Start by clicking on the system and providing your PennKey login, and you should see the following:
"Start by clicking on the system and providing your PennKey login. You should then see the following:"

2021-07-30 04:35 UTC, scovitz commented on docs/nda/dua_tutorial.md
> +In the case of [PING](https://nda.nih.gov/edit_collection.html?id=2607), the type of data is de-identified health information.
put quotations around "de-identified health information"

2021-07-30 04:35 UTC, scovitz commented on docs/nda/dua_tutorial.md
> +Faculty member is Ted and the department is correspondingly Neuropsychiatry.
In our case, the faculty member is Theodore Satterthwaite, and the  department is Neuropsychiatry.

2021-07-30 04:35 UTC, scovitz commented on docs/nda/dua_tutorial.md
> +You should be provided with a research plan which you can either upload or copy into the blank field.
Consult the team to come up with a research plan. This should be a short paragraph. You can either enter that plan in the blank field or upload it as an attachment.

2021-07-30 04:35 UTC, scovitz commented on docs/nda/dua_tutorial.md
> +In the case of [PING](https://nda.nih.gov/edit_collection.html?id=2607), it is funded by the National Institute of Mental Health (NIMH) which is a federal agency. Hence we select **Federally sponsore
Replace "In the case of PING, it is funded..." with "PING is funded..."

2021-07-30 04:35 UTC, scovitz commented on docs/nda/dua_tutorial.md
> +In the case of [PING](https://nda.nih.gov/edit_collection.html?id=2607), the data request is for the purpose of scientific research that is not related or connected to a sponsored research agreement
In the case of PING, the data request is for the purpose of scientific research. This research is neither related nor connected to a sponsored research agreement (SRA), a clinical trail agreement (CTA), ....

2021-07-30 04:35 UTC, scovitz commented on docs/nda/dua_tutorial.md
> +Just relax and wait for a final approval email to pop up in your inbox. Email the completed data use agreement to the [NDA Help Desk](NDAHelp@mail.nih.gov) and you will soon be able to feast on the d
Haha I love "feast on the data" :) 
Great work on this!

2021-07-30 15:14 UTC, TinasheMTapera commented
Once the commits are added I'll test locally

2021-07-30 15:49 UTC, YumekaMengjiaLYU commented
> Once the commits are added I'll test locally

just committed

2021-07-30 16:30 UTC, TinasheMTapera requested changes
Thanks! 2 remaining issues:

- I don't think this file warrants its own folder, so could you move the file from /docs/nda to just /docs/LabHome (so that it reflects the arrangement on the sidebar)?
- Could you fix the `nav_order` in the YAML header of the file? `nav_order` parameter corresponds to where the file appears in the list in the sidebar; this PR will make it go to the top (on top of Onboarding). Could you set `nav_order` lower down on the list

2021-07-30 19:07 UTC, TinasheMTapera requested changes
Sorry _one last thing_ (I promise). The emoji's are not rendering correctly (I don't think they respect the :KEYWORD: notation in jekyll). Could you try and copy paste the actual emoji in -- I was able to get that to work on one of my pages.

2021-07-30 22:27 UTC, YumekaMengjiaLYU commented
> Sorry _one last thing_ (I promise). The emoji's are not rendering correctly (I don't think they respect the :KEYWORD: notation in jekyll). Could you try and copy paste the actual emoji in -- I was able to get that to work on one of my pages.

just saw your comment and replaced them with actual emojis

2021-08-02 14:34 UTC, TinasheMTapera approved these changes

2021-08-02 14:34 UTC, merged